openapi: 3.0.0
info:
  title: Общие данные для интерфейса K2c
  description: |
    Общие данные.
  version: 1.0.

components:
  schemas:
    CrlConnection:
      type: object
      properties:
        start: {type: integer, description: Время начала соединения }
        duration: {type: integer, description: Продолжительность соединения }
        priority: {type: integer, description: Приоритет соединения }
        almanac:
          $ref: '#/components/schemas/Almanac'


    CrlScheduleRow: 
      type: object
      properties:
        start: {type: integer, description: Время начала соединения }
        duration: {type: integer, description: Продолжительность соединения }
      
    CrlSchedule:
      type: object
      properties:
        windows: 
          type: array
          items:
            $ref: '#/components/schemas/CrlScheduleRow'

    CrlSubscribe:
      type: object
      properties:
        ulr: {type: string, description: URL для получения уведомлений}
        subscr_id: {type: integer, description: Идентификатор подписки на статус сеанса КРЛ}
        crl_status: {type: string, enum: [Openning, Opened, Closing, Closed], description: Статус сеанса КРЛ}

    
    AlmanacInfo:
      type: object
      properties:
        time:
          type: integer
          description: Время расчета
        version:
          type: integer
          description: Версия альманаха
        crc:
          type: integer
          description: Контрольная сумма альманаха
    
    AlmanacRecord:
      type: object
      properties:
        value: 
          type: string

    Almanac:
      type: object
      properties:
        info: 
          $ref: '#/components/schemas/AlmanacInfo'
        data:
          type: array
          items:
            $ref: '#/components/schemas/AlmanacRecord'
    
    KaIdFilter:
      type: array
      items:
        type: integer
    
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 127
        message:
          type: string
          example: Сеть недоступна