openapi: 3.0.0
info:
  title: Сервис K2cFSP интерфейса K2c
  description: |
    Сервис МПС ШЛС.
  version: 1.0.
servers:
- url: "{apiRoot}/k2c-service/v1.0"
  variables:
    apiRoot:
      description: Адрес подключения к сервису
      default: http://localhost:8888
paths:
  /almanac/{fsp_id}/{subscr_id}:
    post:
      tags:
      - Almanac
      operationId: AlmanacUpdateNotification
      parameters:
      - name: fsp_id
        in: path
        description: Идентификатор МПС ШЛС
        required: true
        schema:
          type: integer
        example: 10
      - name: subscr_id
        in: path
        description: Идентификатор подписки
        required: true
        schema:
          type: integer
        example: 10  
      requestBody:
        description: Данные альманаха
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: 'K2cCommonData.yaml#/components/schemas/Almanac'
        required: true
      responses:
        "200":
          description: Обновление принято
          content: {}
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: 'K2cCommonData.yaml#/components/schemas/Error'
  
  /crl:
    post:
      tags:
      - CRL
      operationId: CrlSetup
      parameters:
      - name: crl_id
        in: query
        description: Идентификатор запроса на соедиинение КРЛ
        required: true
        explode: false
        schema:
          type: integer
        example: 10
      - name: sc_id
        in: query
        description: Идентификатор КА
        required: true
        explode: false
        schema:
          type: integer
        example: 10  
      requestBody:
        description: Параметры сеанса КРЛ
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CrlConnection'
        required: true
      responses:
        "200":
          description: Запрос на расчет принят
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: {type: integer, description: Идентификатор запроса}
                  url: {type: string, description: URL для управления запросом }
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
  
  /crl/{crl_id}:
    get:
      tags:
      - CRL
      operationId: CrlScheduleGet
      parameters:
      - name: crl_id
        in: path
        description: Идентификатор запроса на соедиинение КРЛ
        required: true
        schema:
          type: integer
        example: 10
      - name: sc_id
        in: query
        description: Идентификатор КА
        required: true
        explode: false
        schema:
          type: integer
        example: 10  
      responses:
        "102":
          description: Расчет в процессе
          content: {}
        "204":
          description: Подходящих соединений не найдено
          content: {}
        "404":
          description: Запрос не найден
          content: {}  
        "200":
          description: Результат расчета
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrlSchedule'  
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - CRL
      operationId: CrlScheduleAction
      parameters:
      - name: crl_id
        in: path
        description: Идентификатор запроса на соедиинение КРЛ
        required: true
        schema:
          type: integer
        example: 10
      - name: sc_id
        in: query
        description: Идентификатор КА
        required: true
        explode: false
        schema:
          type: integer
        example: 10 
      - name: subscr_type
        in: query
        description: Тип подписки
        required: true
        schema: 
          type: string
          enum: [ScheduleReady, CrlStatus]
          default: ScheduleReady   
      requestBody:
        description: Параметры подписки на уведомление 
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/CrlSubscribe'
        required: true
      responses:
        "200":
          description: Подписка зарегестрирована
          content:
            application/json:
              schema:
                type: object
                properties:
                  crl_id: {type: integer, description: Идентификатор запроса}
                  sc_id: {type: integer, description: Идентификатор КА }
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'  
    delete:
      tags:
      - CRL
      operationId: CrlOrStatusCancel
      parameters:
      - name: crl_id
        in: path
        description: Идентификатор запроса на соедиинение КРЛ
        required: true
        schema:
          type: integer
        example: 10
      - name: sc_id
        in: query
        description: Идентификатор КА
        required: true
        explode: false
        schema:
          type: integer
        example: 10 
      - name: subscr_id
        in: query
        description: Идентификатор запроса на уведомление о состоянии КРЛ
        required: false
        explode: false
        schema:
          type: integer
        example: 10  
      responses:
        "200":
          description: Отменено успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  cancel_type: {type: string, enum: [CRL, CrlStatusSubscription], description: Что отменено}
                  id: {type: integer, description: Идентификатор отмененного действия}    
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'

