openapi: 3.0.0
info:
  title: Сервис K2cMCC интерфейса K2c
  description: |
    Сервис ЦУП.
  version: 1.0.
servers:
- url: "{apiRoot}/k2c-service/v1.0"
  variables:
    apiRoot:
      description: Адрес подключения к сервису
      default: http://localhost:8888
paths:
  /almanac:
    get:
      tags:
      - Almanac
      operationId: AlmanacRequest
      parameters:
      - name: fsp_id
        in: query
        description: Идентификатор МПС ШЛС
        required: true
        explode: false
        schema:
          type: integer
        example: 10
      - name: filter
        in: query
        description: Идентификаторы КА
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: integer
      responses:
        "200":
          description: Содержимое альманаха
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Almanac'
        "404":
          description: Данные по запросу альманаха не найдены
          content: {}
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
  /echo:  
    post:
      tags:
      - Ping
      operationId: EchoRequest
      parameters:
      - name: fsp_id
        in: query
        description: Идентификатор МПС ШЛС
        required: true
        explode: false
        schema:
          type: integer
        example: 10
      requestBody:
        description: Параметры альманаха
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/AlmanacInfo'
        required: true
      responses:
        "200":
          description: Echo response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/AlmanacInfo'
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
  
  /almanac/subscribe:
    post:
      tags:
      - Almanac
      operationId: AlmanacUpdateSubscribe
      parameters:
      - name: fsp_id
        in: query
        description: Идентификатор МПС ШЛС
        required: true
        explode: false
        schema:
          type: integer
        example: 10
      - name: subscr_id
        in: query
        description: Идентификатор подписки
        required: true
        explode: false
        schema:
          type: integer
        example: 10  
      requestBody:
        description: Фильтр по идентификаторам КА
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/KaIdFilter'
        required: true
      responses:
        "200":
          description: Подписка зарегистрирована
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: {type: integer, description: Идентификатор подписки}
                  url: {type: string, description: URL подписки }
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
  
  /almanac/subscribe/{subscr_id}:  
    put:
      tags:
      - Almanac
      operationId: AlmanacChangeUpdateSubscription
      parameters:
      - name: fsp_id
        in: query
        description: Идентификатор МПС ШЛС
        required: true
        explode: false
        schema:
          type: integer
        example: 10
      - name: subscr_id
        in: path
        description: Идентификатор подписки
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 10  
      requestBody:
        description: Фильтр по идентификаторам КА
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/KaIdFilter'
        required: true
      responses:
        "200":
          description: Подписка обновлена
          content:
             application/json:
              schema:
                type: integer
                description: Идентификатор подписки        
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - Almanac
      operationId: AlmanacDeleteUpdateSubscription
      parameters:
      - name: fsp_id
        in: query
        description: Идентификатор МПС ШЛС
        required: true
        explode: false
        schema:
          type: integer
        example: 10
      - name: subscr_id
        in: path
        description: Идентификатор подписки
        required: true
        explode: false
        schema:
          type: integer
        example: 10  
      responses:
        "200":
          description: Подписка отменена
          content: {}
        "504":
          description: Таймаут выполнения запроса
          content: {}
        default:
          description: Другие ошибки
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Error'  

components:
  schemas:
    AlmanacInfo:
      type: object
      properties:
        time:
          type: integer
          description: Время расчета
        version:
          type: integer
          description: Версия альманаха
        crc:
          type: integer
          description: Контрольная сумма альманаха
    
    AlmanacRecord:
      type: object
      properties:
        value: 
          type: string

    Almanac:
      type: object
      properties:
        info: 
          $ref: '#/components/schemas/AlmanacInfo'
        data:
          type: array
          items:
            $ref: '#/components/schemas/AlmanacRecord'
    
    KaIdFilter:
      type: array
      items:
        type: integer
    
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 127
        message:
          type: string
          example: Сеть недоступна